### ISSUE TITLE
Snowflake Performance

### ISSUE THREAD

**Issue by jackdreillyvia** [CartoDB/carto-spatial-extension#184]
On Snowflake, the performance of certain functions from here are very poor.

I believe the fix is simple, and it uses caching of  libraries across function calls:

https://docs.snowflake.com/en/developer-guide/udf/javascript/udf-javascript-introduction.html#global-state

For instance, for `LONGLAT_AS_H3`, you can modify the existing code with some `setup` function like so:

```SQL
CREATE OR REPLACE FUNCTION @@SF_PREFIX@@h3._LONGLAT_ASH3
(longitude DOUBLE, latitude DOUBLE, resolution DOUBLE)
RETURNS STRING
LANGUAGE JAVASCRIPT
IMMUTABLE
AS $$
    function setup() {
        @@SF_LIBRARY_LONGLAT_ASH3@@
        h3LibGlobal = h3Lib;
    }
    if (typeof(setup_done) === "undefined") {
        setup();
        setup_done = true;
    }
    if (LONGITUDE == null || LATITUDE == null || RESOLUTION == null) {
        return null;
    }
    const index = h3LibGlobal.geoToH3(Number(LATITUDE), Number(LONGITUDE), Number(RESOLUTION));
    return index;
$$;
```

On my informal benchmarking, adding this caching allows this function to be called 1 Million times in 3-4 seconds, while without caching, it never completes (> 5 minutes and counting).

Have you come across similar performance problems? Do you see any reason **not** to adopt this pattern across all Snowflake calls?

**Comment by vdelacruzb** [comment]
Actually we didn't know about this possibility before, and yes we have come across with many performance problems specially in H3 what make barely usable (specially performing polyfills)
So for sure will try this solution and take this implementation as a reference for all our Snowflake UDFs.

Thanks a lot for this tip.

**Comment by jackdreillyvia** [comment]
> Actually we didn't know about this possibility before, and yes we have come across with many performance problems specially in H3 what make barely usable (specially performing polyfills) So for sure will try this solution and take this implementation as a reference for all our Snowflake UDFs.
> 
> Thanks a lot for this tip.

Let me know how I can be helpful if needed :)

**Comment by martejpad** [comment]
Hi Jack, this is Margara, Product Manager of this project. Just wanted to let you know that we've implemented and deployed in Snowflake your performance optimization proposal. Thanks so much again for this invaluable contribution, it has made a huge difference! :clap:
