### ISSUE TITLE
ST_S2 returning crazy values

### ISSUE THREAD

**Issue by SpencerC** [CartoDB/carto-spatial-extension#29]
```
WITH data AS (SELECT jslibs.s2.ST_S2(ST_GEOGPOINT(-74.006, 40.7128), 12) AS id)
SELECT * FROM data
```
Returns
```
Failed to coerce output value "9926595690882924544" to type INT64: Bad int64 value: 9926595690882924544
```
This seems to be the case for geopoints with longitudes between -60 and -120 and latitudes below about (but not exactly) 40.

**Comment by francois-baptiste** [comment]
Thank you @SpencerC for raising this issue.
Looks like it's a problem of casting uint64 into int64.
The JS UDF should output directly int64 instead of uint64.
I will digg into it.

**Comment by SpencerC** [comment]
Since S2 cell numbers are unsigned, wouldn't it be better to solve the underlying issue and keep the return type `UINT64`?

**Comment by francois-baptiste** [comment]
Sadly enough `uint64` is not a valid type in bigquery.

> We disallow uint, uint64 and uintptr, because they are (potentially) 64-bit unsigned values, so they cannot be accurately represented as a signed 64-bit integer.

That's why I propose to use `int64` with the same binary representation as a  `uint64`.

**Comment by francois-baptiste** [comment]
fixed by #38

**Comment by francois-baptiste** [comment]
Sorry, I just realized that I kept this fix for myself a long time ago and forgot to publish the patch in PR.
Since @vdelacruzb  is currently working on an entire refactor of the project, I PR directly the refactored version.

You can preview the fix as below using my personal GCS bucket:

```
CREATE TEMP FUNCTION latLngToId(latitude FLOAT64, longitude FLOAT64, level NUMERIC) RETURNS INT64 DETERMINISTIC LANGUAGE js
OPTIONS (library=["gs://bigquery-geolib/s2geometry.js"]) AS """
return S2.keyToId(S2.S2Cell.latLngToKey(latitude, longitude, level));
""";
SELECT latLngToId(-74.006, 40.7128, 12)

```

**Comment by francois-baptiste** [comment]
@SpencerC see #39 if you want to output your S2 cells to kepler.gl

**Comment by Algunenano** [comment]
@vdelacruzb Can you confirm if this is fixed and tested with the new code, please?

**Comment by vdelacruzb** [comment]
Yes, this has being tested. And also have a specific integration test entry for this case.
