### ISSUE TITLE
Where can I see the old code for jslibs?

### ISSUE THREAD

**Issue by pedromachados** [CartoDB/carto-spatial-extension#49]
Hi there. 

Is there another branch or repo where I can see the code for the H3 functions available under jslibs?

Also, are the new functions available publicly in BigQuery? Where?

Thanks!

**Comment by SpencerC** [comment]
One of the old master commits maybe?
https://github.com/CartoDB/carto-spatial-extension/tree/18f96426ee864a8ae76488ca16a297b0b712ecdc

**Comment by pedromachados** [comment]
Thanks, @SpencerC is there a branch pointing to this commit? Should we have a tag?

**Comment by SpencerC** [comment]
Found that commit by looking here: https://github.com/CartoDB/carto-spatial-extension/commits/master
I'm not a contributor, so can't help with tag.

**Comment by Algunenano** [comment]
Hi,

You can see the old code here: https://github.com/CartoDB/carto-spatial-extension/tree/de10302395e9f91eb8a8a53fae24e1c71c3220e4

The new code for the H3 module is under the h3 directory: https://github.com/CartoDB/carto-spatial-extension/tree/71821e690fa3e1169e2059809085953c3ef37c27/h3

> Also, are the new functions available publicly in BigQuery? Where?

We are currently finishing testing and reviewing the documentation. I expect they will be available throughout the week (or early next week) under `bqcarto.h3.*` (`bqcartoeu.h3.*` for the EU region). The old functions will keep working under `jslibs` for a long while, but they won't receive any further updates.

**Comment by Jesus89** [comment]
Hey, we have refactored the project structure. You can check the implementation for the H3 module for BigQuery here: https://github.com/CartoDB/carto-spatial-extension/tree/master/modules/h3/bigquery.
