### ISSUE TITLE
Quadint prefix search

### ISSUE THREAD

**Issue by JacobHayes** [CartoDB/carto-spatial-extension#63]
With quadkeys, it's easy to do a string prefix match to perform range queries (ie: `startswith(qk15, qk10)`). Is there a quick equivalent with quadints (ie: sql only)? Converting to quadkey or using `TOPARENT` (bit mask to extract level from parent id) would work, but rather avoid the js UDF in the join.

Use case:
- store a polygon as a collection of low zoom QK cells (perhaps varying zooms, but still non-overlapping) and join to points represented as a high zoom QK cell.

Would also be interested in this for s2 and h3 (though h3 non-nesting isn't ideal).

**Comment by vdelacruzb** [comment]
Hi @JacobHayes, it's true that one of the advantages of using string quadkeys is being able to compare prefix easily. I didn't answer before as keeping support for string quadkey without conversion have to be discussed a bit more with the team. 

I have created a SQL based version of TOPARENT for quadint which is faster than the js version, we will probably just replace it by the current one. Would this meet your needs?

**Comment by JacobHayes** [comment]
Yes, that would be great, thank you!

On a tangent, I'd be happy to contribute a `ST_COVERS(parent, child)` function that does `parent = child or parent = TO PARENT(child, parent & 0x1F)` (TOPARENT errors if cell matches desired zoom, hence the first check) if you all would be open.

**Comment by vdelacruzb** [comment]
Hi @JacobHayes as you see it's in review so if you need the function urgently maybe you can copy paste it in on of your projects. It should arrive during this week for sure though. We are trying to make the deployment to production process more agile.

And regarding contributing, of course, you are welcome to do so. I don't know if you are familiar with the new structure of the project and how to contribute, https://github.com/CartoDB/carto-spatial-extension/blob/master/CONTRIBUTING.md
but if you have any problem creating the tests or anything we can assist you as well.
Regarding the ST_COVERS it would be nice to have that function. Normally we use the prefix ST_ for functions that deals directly with geographies, but on this case it makes sense so we have an equivalent with PostGIS.

**Comment by vdelacruzb** [comment]
@JacobHayes  I'll let you know when the new version of TOPARENT is in production.

**Comment by vdelacruzb** [comment]
Hi @JacobHayes writing just to let you know that the new version of TOPARENT is finally in production so it can be used :).
