### ISSUE TITLE
Inconsistent results between s2 libraries for S2CellId

### ISSUE THREAD

**Issue by jgonzalezferrer** [CartoDB/carto-spatial-extension#97]
According to the s2geometry [documentation](https://s2geometry.io/devguide/s2cell_hierarchy#s2cellid) the S2CellID is a UINT64 type whereas the CARTO [documentation](https://docs.carto.com/spatial-extension-bq/sql-reference/s2/#st_asid) specifies a INT64 type. I've seen in this [issue](https://github.com/CartoDB/carto-spatial-extension/issues/29) that BQ doesn't support UINT64 and that's why you decided to use `int64` with the same binary representation as a `uint64`.

However, I'm getting inconsistent results when using s2 libraries, e.g. in Python:

<img width="552" alt="Screenshot 2021-05-13 at 15 56 25" src="https://user-images.githubusercontent.com/11059180/118135880-ccdeff00-b403-11eb-8305-70f48fcbb180.png">

<img width="581" alt="Screenshot 2021-05-13 at 15 57 02" src="https://user-images.githubusercontent.com/11059180/118135949-dec0a200-b403-11eb-9897-5e1a46c1c8ae.png">

This was also tested in Go.

**Comment by Jesus89** [comment]
Hello @jgonzalezferrer.

Thanks for reporting this bug. A couple of days ago we detected the same issue and tested `BIGNUMERIC` type instead of `INT64` and seems to be fixed with that type.

![](https://user-images.githubusercontent.com/2227572/118139097-5217e300-b407-11eb-85b0-fa399ad64763.png)

We probably deploy the fix tomorrow.

**Comment by francois-baptiste** [comment]
Hi @jgonzalezferrer,
You have just found an example where the binary representation is the same but the decimal representation is different!
If you cast the `int64` into `uint64` you will get the intended result:
```
In [1]: np.int64(-8803593495395696640).astype(np.uint64)
Out[1]: 9643150578313854976
```
I am working with @Jesus89 to provide a getter function to output `S2CellID` as `BIGNUMERIC` , stringified or hexified uint64 but keep in mind that these formats will be less resource efficient than native `INT64` if you process them further with Bigquery.

**Comment by Jesus89** [comment]
Hi @jgonzalezferrer

We have added two new pair of functions to the module:
- TOKEN_FROMID / ID_FROMTOKEN: to support string hex format of the Cell ID. This can be used to render geometries directly like in deck.gl (https://deck.gl/docs/api-reference/geo-layers/s2-layer)
- UINT64REPR_FROM_ID / ID_FROM_UINT64REPR: to support a string uint64 version of the Cell ID. This can be used to see the unsigned representation of the ID. You can also cast to BIGNUMERIC taking into account that it will use more than 64bit to store the index.

More info here: https://docs.carto.com/spatial-extension-bq/sql-reference/s2/
